name: CI

env:
  config: Release
  solutionName: src\i18n.sln
  vsixContainer: ${{ github.workspace }}\POTGenerator.vsix

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ github_actions_build ]
  pull_request:
    branches: [ github_actions_build ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
     
     
     
   # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ windows-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
             
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: echo MSBuild
        run: msbuild -version
              
      - name: Setup NuGet 
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@255f46e14d51fbc603743e2aa2907954463fbeb9
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet  
        run: nuget restore src\i18n.sln
        
      - name: Build the Solution
        run: msbuild  ${{ env.solutionName }} /p:Configuration=${{ env.config }}  /p:DeployExtension=False /verbosity:minimal
        
      - name: Run unit tests
        run:  '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /testcontainer:src\i18n.Tests\bin\Release\i18n.Tests.dll'
      
      - name: Artifacts
        uses: actions/upload-artifact@v2.2.1
        with:
          name: ${{ GITHUB_RUN_ID }} ${{GITHUB_RUN_NUMBER }} ${{ GITHUB_REF }} ${{ GITHUB_SHA }}
          path: |
            src\**\Release\**
        
        
        
