name: NuGet Publish

env:
  config: Release
  solutionName: src\i18n.sln
  
on:  
  push:
    tags:
      - 'release*'

      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on testfsadf
    runs-on: [ windows-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
             
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: echo MSBuild
        run: msbuild -version
              
