name: NuGet Publish

env:
  config: Release
  solutionName: src\i18n.sln
  
on:  
  push:
  # tags:
   #   - 'release*'
    branches: [ nuget_publish ]
#defaults:
 # run:
    #shell: pwsh
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on testfsadffsd
    runs-on: [ windows-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
             
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: echo MSBuild
        run: msbuild -version
        
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      # - name: pws
      #   run: |
      #     $verPre = "2.1.1.1";
      #     $ver = "3.1";

      #     Get-ChildItem 'src\**\AssemblyInfo.cs' -Recurse | ForEach-Object -Process {
      #     (Get-Content $_) `
      #         -replace 'version="(\d+)(\.\d+)(\.\d+)(?:(?:\.\d+)?|(\-\w+)?)?"', ('version="' + $verPre + '"')`
      #         -replace 'AssemblyVersion."(\d+)(\.\d+)(\.\d+)(?:(?:\.\d+)?|(\-\w+)?)?"', ('AssemblyVersion("' + $ver + '"')`
      #         -replace 'AssemblyFileVersion."(\d+)(\.\d+)(\.\d+)(?:(?:\.\d+)?|(\-\w+)?)?"', ('AssemblyFileVersion("' + $ver + '"')`
      #         -replace 'AssemblyInformationalVersion."(\d+)(\.\d+)(\.\d+)(?:(?:\.\d+)?|(\-\w+)?)?"', ('AssemblyInformationalVersion("' + $verPre + '"')`
      #       | Out-File $_ -Encoding utf8
      #     }
      #   shell: powershell
        #working-directory: ./src
          
        
        
