name: Sandbox

env:
  config: Release
  solutionName: src\i18n.sln
  
on:  
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: [ windows-latest ]
    steps:
      - name: run script
        run: updateVersion.ps1
        shell: powershell